version = 1

exclude_patterns = [
  "gwaihir/scripts/examples/*",
  "gwaihir/scripts/*",
  "gwaihir/runner/*",
  "gwaihir/sixs/*",
  "gwaihir/facet_analysis.py"
]

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "autopep8"
enabled = true